version: "3.3"
services:
  notes-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notes_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: password
    entrypoint:
      - bash
      - -c
      - |
        mysql_ready() {
          mysqladmin ping --host=mysql --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1
        }

        while !(mysql_ready)
        do
          sleep 3
          echo "waiting for mysql ..."
        done
        echo "mysql is UP"
        java -jar /app/notes-rest-service-0.0.1-SNAPSHOT.jar
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=password
