package com.notes.notesrestservice;

import org.springframework.data.repository.CrudRepository;

import com.notes.notesrestservice.Note;

// Auto-generated by Spring
public interface NoteRepository extends CrudRepository<Note, Integer> {

}
